# docker-compose.yml

services:
  redis:
    volumes:
      - ./:/app
    image: redis:7-alpine
    container_name: bis-redis
    command: ["redis-server", "--save", "", "--appendonly", "no"]
    ports: ["6379:6379"]
    healthcheck:
      test: ["CMD", "/usr/local/bin/redis-cli", "-h", "127.0.0.1", "-p", "6379", "ping"]
      interval: 5s
      timeout: 3s
      retries: 30
      start_period: 5s
    restart: unless-stopped

  api:
    volumes:
      - ./:/app
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bis-api
    command: >
      uvicorn app.main:app --host 0.0.0.0 --port 8000 --proxy-headers
    env_file: .env
    environment:
      DATABASE_URL: postgresql+psycopg2://postgres:postgres@172.30.1.66:5432/new_dashboard
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/1
    ports: ["8000:8000"]
    depends_on: 
      redis:
        condition: service_healthy
    restart: unless-stopped

  worker:
    volumes:
      - ./:/app
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bis-worker
    command: celery -A app.celery_app.celery_app worker --loglevel=INFO
    env_file: .env
    environment:
      DATABASE_URL: postgresql+psycopg2://postgres:postgres@172.30.1.66:5432/new_dashboard
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/1
    depends_on: 
      redis:
        condition: service_healthy
    restart: unless-stopped